import = ["~/.config/alacritty/themes/themes/rose-pine.toml"]

live_config_reload = true

[window]
decorations = "Buttonless"
dynamic_title = true
dynamic_padding = true
opacity = 1
option_as_alt = "Both"
startup_mode = "Windowed"
[window.dimensions]
columns = 82
lines = 25
[window.padding]
x = 25
y = 25

[scrolling]
history = 10000
multiplier = 3

[font]
size = 16.0
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"
[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"
[font.offset]
x = 0
y = 0
[font.glyph_offset]
x = 0
y = 0

[cursor]
[cursor.style]
shape = "Block"
