import: 
 - "~/.config/alacritty/rose-pine.yml"
window:
  dimensions:
    columns: 82
    lines: 25
  padding:
    x: 25
    y: 25

  dynamic_padding: true
  decorations: buttonless 
  opacity: 1
  startup_mode: Windowed
  dynamic_title: true
  option_as_alt: Both

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: JetBrainsMono Nerd Font 
    style: Regular
  bold:
    family: JetBrainsMono Nerd Font 
    style: Bold
  italic:
    family: JetBrainsMono Nerd Font 
    style: Italic

  size: 16.0
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0

cursor:
  style:
    shape: Block
    blinking: On
  unfocused_hollow: true

live_config_reload: true
